//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int courseId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string tutor { get; set; }
        public string level { get; set; }
        public string price { get; set; }
        public string type { get; set; }
        public string startTime { get; set; }
        public string schedule { get; set; }
        public string rate { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public string location { get; set; }
        public string url { get; set; }
    }
}
